# Generated by Django 3.0.5 on 2020-04-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_itemlist_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
