# Generated by Django 3.0.5 on 2020-04-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20200407_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
